require conf/distro/poky.conf

DISTRO = "custom-image"
DISTRO_NAME = "Custom Image (ITI Project Reference Distro)"

MAINTAINER = "Yasmine <yasmine@lists.yoctoproject.org>"

DISTRO_FEATURES:append = " systemd usrmerge wifi wayland opengl pam"
DISTRO_FEATURES_BACKFILL:append = " sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"

CMDLINE:append = " console=ttyAMA1,115200"

PACKAGECONFIG:append:pn-qtbase = " wayland"

APPEND = "quiet splash logo.nologo vt.global_cursor_default=0"

RPI_EXTRA_CONFIG = "\ndtoverlay=vc4-fkms-v3d\ngpu_mem=128\n"
