require conf/distro/poky.conf

DISTRO = "custom-image"
DISTRO_NAME = "Custom Image (ITI Project Reference Distro)"

MAINTAINER = "Yasmine <yasmine@lists.yoctoproject.org>"

DISTRO_FEATURES:append = " systemd usrmerge wifi"
DISTRO_FEATURES_BACKFILL:append = " sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"

CMDLINE:append = " console=ttyAMA1,115200"