BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-task-one"
BBFILE_PATTERN_meta-task-one := "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-task-one = "6"

LAYERDEPENDS_meta-task-one = "core"
LAYERSERIES_COMPAT_meta-task-one = "scarthgap"